DROP TABLE IF EXISTS MEMB RESTRICT;
DROP TABLE IF EXISTS TCHER RESTRICT;
DROP TABLE IF EXISTS CHAT RESTRICT;
DROP TABLE IF EXISTS PROMOTION RESTRICT;
DROP TABLE IF EXISTS TCHER_TRAINER RESTRICT;
DROP TABLE IF EXISTS PROMOTIONIMG RESTRICT;
DROP TABLE IF EXISTS SCHEDULE RESTRICT;
DROP TABLE IF EXISTS MEMB_MANAGE RESTRICT;
DROP TABLE IF EXISTS TCHER_REVIEW RESTRICT;
DROP TABLE IF EXISTS ALERT RESTRICT;
CREATE TABLE MEMB (
  MNO         INTEGER      NOT NULL COMMENT '회원번호',
  ID          VARCHAR(50)  NOT NULL COMMENT '아이디',
  EMAIL       VARCHAR(40)  NOT NULL COMMENT '이메일',
  ACCOUNTTYPE INTEGER      NOT NULL COMMENT '가입유형',
  IMG         VARCHAR(255) NULL     COMMENT '사진경로',
  PWD         VARCHAR(255) NOT NULL COMMENT '비밀번호',
  NAME        VARCHAR(50)  NOT NULL COMMENT '이름',
  MTYPE       INT(11)      NOT NULL COMMENT '회원유형'
)
COMMENT '회원';

ALTER TABLE MEMB
  ADD CONSTRAINT PK_MEMB
    PRIMARY KEY (
      MNO
    );

CREATE UNIQUE INDEX UIX_MEMB
  ON MEMB (
    ID ASC
  );

CREATE UNIQUE INDEX UIX_MEMB2
  ON MEMB (
    EMAIL ASC,
    ACCOUNTTYPE ASC
  );

ALTER TABLE MEMB
  MODIFY COLUMN MNO INTEGER NOT NULL AUTO_INCREMENT COMMENT '회원번호';

CREATE TABLE TCHER (
  TNO           INTEGER      NOT NULL COMMENT '강사회원번호',
  INTRODUCTION  TEXT         NULL     COMMENT '소개',
  COMPANY       VARCHAR(50)  NOT NULL COMMENT '상호명',
  ZIPCODE       VARCHAR(255) NOT NULL COMMENT '우편번호',
  COMADDR       VARCHAR(255) NOT NULL COMMENT '근무지주소',
  COMDETAILADDR VARCHAR(255) NOT NULL COMMENT '상세주소',
  SPONO         INTEGER      NULL     COMMENT '운동명'
)
COMMENT '강사';

ALTER TABLE TCHER
  ADD CONSTRAINT PK_TCHER
    PRIMARY KEY (
      TNO
    );

CREATE TABLE CHAT (
  CNO     INTEGER      NOT NULL COMMENT '채팅번호',
  MNO     INTEGER      NOT NULL COMMENT '회원번호',
  TNO     INTEGER      NOT NULL COMMENT '강사회원번호',
  WHOSEND INTEGER      NOT NULL COMMENT '보낸사람',
  MSG     TEXT         NOT NULL COMMENT '메세지',
  DATE    VARCHAR(255) NOT NULL COMMENT '일시',
  CONFIRM BOOLEAN      NOT NULL COMMENT '읽은여부'
)
COMMENT '쪽지';

ALTER TABLE CHAT
  ADD CONSTRAINT PK_CHAT
    PRIMARY KEY (
      CNO
    );

ALTER TABLE CHAT
  MODIFY COLUMN CNO INTEGER NOT NULL AUTO_INCREMENT COMMENT '채팅번호';

CREATE TABLE PROMOTION (
  PNO     INTEGER      NOT NULL COMMENT '프로모션 번호',
  TITL    VARCHAR(50)  NOT NULL COMMENT '제목',
  PRIC    INTEGER      NOT NULL COMMENT '가격',
  CONTENT TEXT         NOT NULL COMMENT '내용',
  SDT     VARCHAR(255) NOT NULL COMMENT '시작날짜',
  EDT     VARCHAR(255) NOT NULL COMMENT '종료날짜',
  TNO     INTEGER      NOT NULL COMMENT '강사회원번호',
  lat     DOUBLE       NULL     COMMENT '위도',
  lng     DOUBLE       NULL     COMMENT '경도',
  expire  INTEGER      NULL     COMMENT '만료여부'
)
COMMENT '프로모션';

ALTER TABLE PROMOTION
  ADD CONSTRAINT PK_PROMOTION
    PRIMARY KEY (
      PNO
    );

ALTER TABLE PROMOTION
  MODIFY COLUMN PNO INTEGER NOT NULL AUTO_INCREMENT COMMENT '프로모션 번호';

CREATE TABLE TCHER_TRAINER (
  TRANO    INTEGER      NOT NULL COMMENT '개인트레이너일련번호',
  MNO      INTEGER      NOT NULL COMMENT '회원번호',
  TNO      INTEGER      NOT NULL COMMENT '강사회원번호',
  PNO      INTEGER      NOT NULL COMMENT '프로모션 번호',
  SDT      VARCHAR(255) NOT NULL COMMENT '시작일',
  EDT      VARCHAR(255) NOT NULL COMMENT '종료일',
  PERIOD   INTEGER      NOT NULL COMMENT '기간',
  CONFIRM  BOOLEAN      NOT NULL COMMENT '수락여부',
  REQDATE  VARCHAR(255) NOT NULL COMMENT '요청날짜',
  WISHTIME INTEGER      NOT NULL COMMENT '원하는타임',
  WRITEREV BOOLEAN      NULL     COMMENT '리뷰작성'
)
COMMENT '개인트레이너';

ALTER TABLE TCHER_TRAINER
  ADD CONSTRAINT PK_TCHER_TRAINER
    PRIMARY KEY (
      TRANO
    );


CREATE UNIQUE INDEX UIX_TCHER_TRAINER
  ON TCHER_TRAINER (
  );

ALTER TABLE TCHER_TRAINER
  MODIFY COLUMN TRANO INTEGER NOT NULL AUTO_INCREMENT COMMENT '개인트레이너일련번호';

CREATE TABLE PROMOTIONIMG (
  IMGNO    INTEGER      NOT NULL COMMENT '프로모션사진일련번호',
  PNO      INTEGER      NOT NULL COMMENT '프로모션 번호',
  PIMG     VARCHAR(255) NOT NULL COMMENT '사진경로',
  titlePic BOOLEAN      NULL     COMMENT '타이틀사진유무'
)
COMMENT '프로모션사진';

ALTER TABLE PROMOTIONIMG
  ADD CONSTRAINT PK_PROMOTIONIMG
    PRIMARY KEY (
      IMGNO
    );

ALTER TABLE PROMOTIONIMG
  MODIFY COLUMN IMGNO INTEGER NOT NULL AUTO_INCREMENT COMMENT '프로모션사진일련번호';

CREATE TABLE SCHEDULE (
  SCHNO INTEGER      NOT NULL COMMENT '일정번호',
  TNO   INTEGER      NOT NULL COMMENT '강사회원번호',
  DAY   VARCHAR(255) NOT NULL COMMENT '요일',
  TIME  VARCHAR(255) NOT NULL COMMENT '시간'
)
COMMENT '일정';

ALTER TABLE SCHEDULE
  ADD CONSTRAINT PK_SCHEDULE
    PRIMARY KEY (
      SCHNO
    );

CREATE UNIQUE INDEX UIX_SCHEDULE
  ON SCHEDULE (
    TNO ASC,
    DAY ASC,
    TIME ASC
  );

ALTER TABLE SCHEDULE
  MODIFY COLUMN SCHNO INTEGER NOT NULL AUTO_INCREMENT COMMENT '일정번호';

CREATE TABLE MEMB_MANAGE (
  MEALNO   INTEGER      NOT NULL COMMENT '회원식단일련번호',
  MEALTYPE VARCHAR(255) NOT NULL COMMENT '끼니',
  MEALPIC  VARCHAR(255) NOT NULL COMMENT '식단사진',
  MEALKCAL INTEGER      NOT NULL COMMENT '칼로리',
  MEALNAME VARCHAR(50)  NOT NULL COMMENT '식단이름',
  DATE     DATE         NOT NULL COMMENT '날짜',
  DAY      VARCHAR(255) NOT NULL COMMENT '요일별명',
  CONFIRM  BOOLEAN      NOT NULL COMMENT '확인여부',
  TRANO    INTEGER      NOT NULL COMMENT '개인트레이너일련번호'
)
COMMENT '회원식단관리';

ALTER TABLE MEMB_MANAGE
  ADD CONSTRAINT PK_MEMB_MANAGE
    PRIMARY KEY (
      MEALNO
    );

ALTER TABLE MEMB_MANAGE
  MODIFY COLUMN MEALNO INTEGER NOT NULL AUTO_INCREMENT COMMENT '회원식단일련번호';

CREATE TABLE TCHER_REVIEW (
  REVIEWNO INTEGER      NOT NULL COMMENT '강사리뷰번호',
  TRANO    INTEGER      NOT NULL COMMENT '개인트레이너일련번호',
  SCORE    INTEGER      NOT NULL COMMENT '평점',
  REVIEW   TEXT         NULL     COMMENT '코멘트',
  PNO      INTEGER      NULL     COMMENT '프로모션번호',
  PROTITL  VARCHAR(255) NULL     COMMENT '프로모션제목',
  DATE     VARCHAR(255) NULL     COMMENT '리뷰등록시간'
)
COMMENT '강사리뷰';

ALTER TABLE TCHER_REVIEW
  ADD CONSTRAINT PK_TCHER_REVIEW
    PRIMARY KEY (
      REVIEWNO
    );

ALTER TABLE TCHER_REVIEW
  MODIFY COLUMN REVIEWNO INTEGER NOT NULL AUTO_INCREMENT COMMENT '강사리뷰번호';

CREATE TABLE ALERT (
  ALNO      INTEGER      NOT NULL COMMENT '알람일련번호',
  OTHERNAME VARCHAR(50)  NOT NULL COMMENT '누가',
  MYMNO     INTEGER      NOT NULL COMMENT '누구한테',
  KINDS     VARCHAR(255) NOT NULL COMMENT '무엇을',
  DATE      VARCHAR(50)  NOT NULL COMMENT '시간',
  CONFIRM   BOOLEAN      NOT NULL COMMENT '확인여부',
  TYPE      INTEGER      NOT NULL COMMENT '유형',
  OTHERMNO  INTEGER      NOT NULL COMMENT '상대방번호'
)
COMMENT '알람';

ALTER TABLE ALERT
  ADD CONSTRAINT PK_ALERT
    PRIMARY KEY (
      ALNO
    );

ALTER TABLE ALERT
  MODIFY COLUMN ALNO INTEGER NOT NULL AUTO_INCREMENT COMMENT '알람일련번호';

ALTER TABLE TCHER
  ADD CONSTRAINT FK_MEMB_TO_TCHER
    FOREIGN KEY (
      TNO
    )
    REFERENCES MEMB (
      MNO
    );

ALTER TABLE CHAT
  ADD CONSTRAINT FK_MEMB_TO_CHAT
    FOREIGN KEY (
      MNO
    )
    REFERENCES MEMB (
      MNO
    );

ALTER TABLE CHAT
  ADD CONSTRAINT FK_TCHER_TO_CHAT
    FOREIGN KEY (
      TNO
    )
    REFERENCES TCHER (
      TNO
    );

ALTER TABLE PROMOTION
  ADD CONSTRAINT FK_TCHER_TO_PROMOTION
    FOREIGN KEY (
      TNO
    )
    REFERENCES TCHER (
      TNO
    );

ALTER TABLE TCHER_TRAINER
  ADD CONSTRAINT FK_MEMB_TO_TCHER_TRAINER
    FOREIGN KEY (
      MNO
    )
    REFERENCES MEMB (
      MNO
    );

ALTER TABLE TCHER_TRAINER
  ADD CONSTRAINT FK_TCHER_TO_TCHER_TRAINER
    FOREIGN KEY (
      TNO
    )
    REFERENCES TCHER (
      TNO
    );

ALTER TABLE TCHER_TRAINER
  ADD CONSTRAINT FK_PROMOTION_TO_TCHER_TRAINER
    FOREIGN KEY (
      PNO
    )
    REFERENCES PROMOTION (
      PNO
    );

ALTER TABLE PROMOTIONIMG
  ADD CONSTRAINT FK_PROMOTION_TO_PROMOTIONIMG
    FOREIGN KEY (
      PNO
    )
    REFERENCES PROMOTION (
      PNO
    );

ALTER TABLE SCHEDULE
  ADD CONSTRAINT FK_TCHER_TO_SCHEDULE
    FOREIGN KEY (
      TNO
    )
    REFERENCES TCHER (
      TNO
    );

ALTER TABLE MEMB_MANAGE
  ADD CONSTRAINT FK_TCHER_TRAINER_TO_MEMB_MANAGE
    FOREIGN KEY (
      TRANO
    )
    REFERENCES TCHER_TRAINER (
      TRANO
    );

ALTER TABLE TCHER_REVIEW
  ADD CONSTRAINT FK_TCHER_TRAINER_TO_TCHER_REVIEW
    FOREIGN KEY (
      TRANO
    )
    REFERENCES TCHER_TRAINER (
      TRANO
    );
